env:
  global:
    - secure:
      XVSm+sZwXIh7S2Nn01FPyh7HKkFS/ZZ0YL0e1PODad6X17ytr0DPw/fA2KAHNN+SB6qC6e3cbsVSXxpaZsDlRYBmxRew8WFN00Fvh/jQ4izJx etc 

script:
  - docker build --target test --tag my-test-image .
  - docker run my-test-image tests
  - docker run -e TRELLO_API_KEY -e TRELLO_API_SECRET -e TRELLO_BOARD_ID my-test-image tests_e2e